enabled = false

[it]
title = "Agosto Bruggese"
[[it.items]]
name = "Torneo di Ping Pong"
date = "10 Agosto"
time = "15:00"
[[it.items]]
name = "Torneo di Basket"
date = "15 Agosto"
time = "16:00"
[[it.items]]
name = "Festa del Paese"
date = "16 Agosto"
time = "Tutto il giorno"

[en]
title = "August in Bruggi"
[[en.items]]
name = "Ping Pong Tournament"
date = "August 10th"
time = "3:00 PM"
[[en.items]]
name = "Basketball Tournament"
date = "August 15th"
time = "4:00 PM"
[[en.items]]
name = "Village Festival"
date = "August 16th"
time = "All day"
