[[images]]
url = "/static/img/michi/WhatsApp Image 2026-01-02 at 15.21.13-1.jpeg"
author = "michigiudici"

[[images]]
url = "/static/img/jo/WhatsApp Image 2026-01-02 at 15.20.37.jpeg"
author = "jonathan_n78"

[[images]]
url = "/static/img/jo/WhatsApp Image 2026-01-02 at 15.20.53.jpeg"
author = "jonathan_n78"

[[images]]
url = "/static/img/jo/WhatsApp Image 2026-01-02 at 15.22.54-2.jpeg"
author = "jonathan_n78"

[[images]]
url = "/static/img/jo/WhatsApp Image 2026-01-02 at 15.22.54-3.jpeg"
alt = "Trail monte Bogleglio"
author = "jonathan_n78"

[[images]]
url = "/static/img/michi/WhatsApp Image 2026-01-02 at 15.21.13-2.jpeg"
author = "michigiudici"

[[images]]
url = "/static/img/michi/WhatsApp Image 2026-01-02 at 15.21.13.jpeg"
author = "michigiudici"

[[images]]
url = "/static/img/jo/WhatsApp Image 2026-01-02 at 15.22.54-4.jpeg"
author = "jonathan_n78"

[[images]]
url = "/static/img/jo/WhatsApp Image 2026-01-02 at 15.22.54-5.jpeg"
author = "jonathan_n78"

[[images]]
url = "/static/img/jo/WhatsApp Image 2026-01-02 at 15.22.54-6.jpeg"
author = "jonathan_n78"

[[images]]
url = "/static/img/jo/WhatsApp Image 2026-01-02 at 15.22.54-9.jpeg"
author = "jonathan_n78"

[[images]]
url = "/static/img/jo/WhatsApp Image 2026-01-02 at 15.22.54-giusepp.jpeg"
author = "jonathan_n78"

[[images]]
url = "/static/img/jo/WhatsApp Image 2026-01-02 at 15.22.54.jpeg"
author = "jonathan_n78"
