[[images]]
url = "/static/img/gallery-peaks.jpg"
alt = "Snowy mountain peaks"
author = "mountain_lover"

[[images]]
url = "img/gallery-dish.jpg"
alt = "Traditional dish"

[[images]]
url = "img/gallery-hiker.jpg"
alt = "Hiker view"

[[images]]
url = "img/gallery-river.jpg"
alt = "River valley"
